name: Clang-tidy static analyzer check
run-name: ${{github.actor}} is running Code check.

on:
  push: {}

jobs:
  job:
    name: Clang-tidy Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: sudo apt update && sudo apt -y install clang-tidy

